//! Brev core.
//!
//! Everything that touches message content lives in this crate: the
//! encrypted store, the crypto, and the `Locked`/`Unlocked` session state.
//! The UniFFI surface is [`ping`], [`limits`], [`Brev`] and [`OpenText`]
//! (`ffi.rs`); the Phase 2 echo contacts are in `echo.rs`.
//!
//! `unsafe_code = "forbid"` is set at the workspace level. The UniFFI
//! scaffolding generated by `setup_scaffolding!` is the only code in this
//! crate that crosses the FFI boundary, and it is generated, not written.

#![forbid(unsafe_code)]

uniffi::setup_scaffolding!();

/// Every Rust heap block is zeroed when it is freed, including the
/// `RustBuffer`s Swift frees through UniFFI (CLAUDE.md §3.1). Safe code
/// here: the `unsafe impl` is inside the approved `zeroizing-alloc` crate.
#[global_allocator]
static ALLOC: zeroizing_alloc::ZeroAlloc<std::alloc::System> =
    zeroizing_alloc::ZeroAlloc(std::alloc::System);

mod crypto;
mod echo;
mod ffi;
mod store;
mod transport;

pub use brev_proto::Envelope;
pub use crypto::Plaintext;
pub use ffi::{
    limits, Brev, BrevError, ContactRow, Limits, MessageRow, OpenText, ThreadRow, CHUNK, MAX_BODY,
    MAX_SUBJECT,
};
pub use store::{
    Contact, Core, Delivery, IdentityId, Message, MessageId, PublicBundle, Thread, ThreadId,
};
pub use transport::{MockTransport, Transport};

/// Errors from the core. None of them carries content.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// The core is locked; unlock with the DEK first.
    #[error("locked")]
    Locked,
    /// `unlock` was given a DEK that does not open this store, or all zeros.
    #[error("wrong key")]
    WrongKey,
    /// Authenticated decryption failed (tampered envelope, tampered or moved
    /// store row) or a key agreement was non-contributory.
    #[error("decryption failed")]
    Crypto,
    /// No row with that id (including `new_thread` for a non-contact); or an
    /// envelope from someone who is not a contact.
    #[error("not found")]
    NotFound,
    /// `receive` was given a message id that is already stored (a replay),
    /// or `add_contact` a contact that is already there.
    #[error("duplicate")]
    Duplicate,
    /// Input or envelope has the wrong shape: relative store path, all-zero
    /// DEK at `create`, misaddressed envelope, bad payload, subject over
    /// 65535 bytes, signing key not 1..=255 bytes, own identity as a contact,
    /// thread owned by another contact, a column value too large to pad.
    #[error("malformed")]
    Malformed,
    /// The file is not a Brev store of this schema version, or its schema
    /// has been altered (for example a planted trigger).
    #[error("not a brev store")]
    Corrupt,
    /// The [`Signer`] refused or failed (for example Touch ID cancelled).
    #[error("signing failed")]
    Signing,
    /// The OS random number generator failed.
    #[error("randomness unavailable")]
    Rng,
    /// Creating the store file failed (including: it already exists).
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    /// SQLite error. Only ids, metadata and ciphertext ever reach SQLite, so
    /// its messages cannot contain content.
    #[error("storage: {0}")]
    Storage(rusqlite::Error),
}

impl From<rusqlite::Error> for Error {
    fn from(e: rusqlite::Error) -> Self {
        match e {
            rusqlite::Error::QueryReturnedNoRows => Error::NotFound,
            e => Error::Storage(e),
        }
    }
}

/// Fills an envelope's signature slot.
///
/// Phase 1 tests implement it with an Ed25519 key. From Phase 3 the Secure
/// Enclave signature arrives through the two-step flow of CLAUDE.md §5
/// (`sign_request`/`attach_signature`, built on [`Envelope::signed_bytes`]
/// and [`Envelope::signature`]), so that `send` never holds the core during
/// a Touch ID prompt. The envelope format does not change.
pub trait Signer {
    /// Signs `signed_bytes` (from [`Envelope::signed_bytes`]) and returns the
    /// raw signature to store in [`Envelope::signature`]. Returns
    /// [`Error::Signing`] if the user or the key refuses.
    fn sign(&self, signed_bytes: &[u8]) -> Result<Vec<u8>, Error>;
}

/// Name reported by [`ping`] so the app can prove it reached the Rust core.
const CORE_NAME: &str = "brev-core";

/// Liveness check for the Rust core.
///
/// Returns a short, content-free string that the Swift app logs at launch.
/// Never carries message content or key material.
#[uniffi::export]
pub fn ping() -> String {
    format!("{CORE_NAME} {} ok", env!("CARGO_PKG_VERSION"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ping_reports_core_and_version() {
        let reply = ping();
        assert!(reply.starts_with("brev-core "));
        assert!(reply.ends_with(" ok"));
        assert!(reply.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn ping_is_pure_ascii_and_short() {
        let reply = ping();
        assert!(reply.is_ascii());
        assert!(reply.len() < 64);
    }
}
