//! Brev core.
//!
//! Everything that touches message content lives in this crate: the
//! encrypted store, the crypto, and the `Locked`/`Unlocked` session state.
//! The Swift app only ever talks to it through the UniFFI surface below.
//!
//! Phase 0 exposes a single `ping()` so the whole toolchain (cargo →
//! uniffi-bindgen → Xcode) can be proven end to end before any content
//! handling exists.
//!
//! `unsafe_code = "forbid"` is set at the workspace level. The UniFFI
//! scaffolding generated by `setup_scaffolding!` is the only code in this
//! crate that crosses the FFI boundary, and it is generated, not written.

#![forbid(unsafe_code)]

uniffi::setup_scaffolding!();

/// Name reported by [`ping`] so the app can prove it reached the Rust core.
const CORE_NAME: &str = "brev-core";

/// Liveness check for the Rust core.
///
/// Returns a short, content-free string that the Swift app logs at launch.
/// Never carries message content or key material.
#[uniffi::export]
pub fn ping() -> String {
    format!("{CORE_NAME} {} ok", env!("CARGO_PKG_VERSION"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ping_reports_core_and_version() {
        let reply = ping();
        assert!(reply.starts_with("brev-core "));
        assert!(reply.ends_with(" ok"));
        assert!(reply.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn ping_is_pure_ascii_and_short() {
        let reply = ping();
        assert!(reply.is_ascii());
        assert!(reply.len() < 64);
    }
}
