//! Brev core: the mail layer (package brev-mail, library `brev_core`).
//!
//! Identity, contacts, threads and letters, the message crypto and the
//! relay client, on top of brev-vault, which holds the encrypted store, the
//! DEK and its `Locked`/`Unlocked` state, the column crypto, the padding and
//! the zeroing global allocator. The UniFFI surface is [`ping`], [`limits`],
//! [`Brev`] and [`OpenText`] (`ffi.rs`); the relay client is in `relay.rs`
//! (docs/PHASE3_DESIGN.md §5). Phase 4 (docs/PHASE4_DESIGN.md §5) adds
//! contact approval, invites and *Blokker*.
//!
//! `unsafe_code = "forbid"` is set at the workspace level. The UniFFI
//! scaffolding generated by `setup_scaffolding!` is the only code in this
//! crate that crosses the FFI boundary, and it is generated, not written.

#![forbid(unsafe_code)]

uniffi::setup_scaffolding!();

mod crypto;
mod ffi;
mod relay;
mod store;
#[cfg(test)]
mod test_keys;
mod transport;

pub use brev_proto::Envelope;
pub use brev_vault::Plaintext;
pub use ffi::{
    limits, Brev, BrevError, ContactInfo, ContactRow, EnvironmentReport, InviteInfo, KeyOrigin,
    Limits, MeInfo, MessageRow, OpenText, ReportField, RequestRow, SyncResult, ThreadRow, CHUNK,
    MAX_BODY, MAX_SUBJECT,
};
pub use store::{
    Contact, ContactId, Core, IdentityId, Letter, Message, MessageId, PublicBundle, Thread,
    ThreadId,
};
#[cfg(any(test, feature = "test-hooks"))]
pub use transport::MockTransport;
pub use transport::{NetError, Transport};

/// Errors from the core. None of them carries content.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    /// The core is locked; unlock with the DEK first.
    #[error("locked")]
    Locked,
    /// `unlock` was given a DEK that does not open this store, or all zeros.
    #[error("wrong key")]
    WrongKey,
    /// Authenticated decryption failed (tampered envelope, tampered or moved
    /// store row), a key agreement was non-contributory, or an envelope's
    /// signature does not verify with its sender's pinned key.
    #[error("decryption failed")]
    Crypto,
    /// No row with that id, or an envelope from someone who is not a
    /// contact.
    #[error("not found")]
    NotFound,
    /// `receive` was given a message id that is already stored (a replay),
    /// `add_contact` a contact or address that is already there,
    /// `accept_new_key` a key that belongs to another contact, or
    /// `set_address` an address when one is stored (addresses are
    /// permanent).
    #[error("duplicate")]
    Duplicate,
    /// Input or envelope has the wrong shape: relative store path, all-zero
    /// DEK at `create`, misaddressed envelope, bad payload or padding,
    /// subject over 65535 bytes, a signing key that is not an uncompressed
    /// P-256 point, own identity or address as a contact, thread owned by
    /// another contact, a value too large to pad, an address that breaks
    /// the rules, a relay URL other than `http://127.0.0.1:<port>`.
    #[error("malformed")]
    Malformed,
    /// The file is not a Brev store of this schema version, or its schema
    /// has been altered (for example a planted trigger), or a local row is
    /// damaged or swapped (a contact's bundle that does not match its tag).
    #[error("not a brev store")]
    Corrupt,
    /// A signature from the Secure Enclave is not valid DER, or not by the
    /// own identity key.
    #[error("signing failed")]
    Signing,
    /// The OS random number generator failed.
    #[error("randomness unavailable")]
    Rng,
    /// Creating the store file failed (including: it already exists).
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    /// SQLite error. Only ids, metadata and ciphertext ever reach SQLite, so
    /// its messages cannot contain content.
    #[error("storage: {0}")]
    Storage(rusqlite::Error),
    /// The relay returned a key for a pinned contact that is not the pinned
    /// one, or the key change has not been accepted (docs/PHASE3_DESIGN.md
    /// §6.3), or an acceptance names another code than the pending one.
    #[error("key changed")]
    KeyChanged,
    /// The relay refused a registration: the address is taken.
    #[error("address taken")]
    AddressTaken,
    /// The relay could not be reached, timed out, failed (5xx) or answered
    /// something that is not what the endpoint gives.
    #[error("network")]
    Network,
    /// The relay refused a request (a 4xx other than those above).
    #[error("refused")]
    Refused,
    /// The store's folder is held by another open store (brev-vault's
    /// directory lock).
    #[error("busy")]
    Busy,
    /// Not safe to decrypt here: the folder is not mode 0700 or `brev.db`
    /// not 0600, or the process has a `DYLD_*` variable or no
    /// `MallocScribble=1` (brev-vault's launch guard).
    #[error("unsafe")]
    Unsafe,
    /// The contact does not take the user's letters (not approved yet, or
    /// declined; the relay answers both alike), or the user blocked the
    /// contact (docs/PHASE4_DESIGN.md §5.3).
    #[error("not approved")]
    NotApproved,
    /// The relay's daily limit for this kind of request is reached.
    #[error("rate limited")]
    RateLimited,
    /// An invite code that does not parse, or that the relay does not know
    /// (unknown, used or expired), or no opened invite where one is needed.
    #[error("invite invalid")]
    InviteInvalid,
    /// The relay's answer to an invite code does not match the code: its
    /// form (root or not), the inviter's address or the key fingerprint.
    #[error("invite mismatch")]
    InviteMismatch,
}

impl From<rusqlite::Error> for Error {
    fn from(e: rusqlite::Error) -> Self {
        match e {
            rusqlite::Error::QueryReturnedNoRows => Error::NotFound,
            e => Error::Storage(e),
        }
    }
}

/// Each vault error is the variant of the same name.
impl From<brev_vault::Error> for Error {
    fn from(e: brev_vault::Error) -> Self {
        use brev_vault::Error as V;
        match e {
            V::Locked => Error::Locked,
            V::WrongKey => Error::WrongKey,
            V::Crypto => Error::Crypto,
            V::NotFound => Error::NotFound,
            V::Malformed => Error::Malformed,
            V::Corrupt => Error::Corrupt,
            V::Rng => Error::Rng,
            V::Io(e) => Error::Io(e),
            V::Storage(e) => Error::Storage(e),
            V::Busy => Error::Busy,
            V::Unsafe => Error::Unsafe,
        }
    }
}

/// Name reported by [`ping`] so the app can prove it reached the Rust core.
const CORE_NAME: &str = "brev-core";

/// Liveness check for the Rust core.
///
/// Returns a short, content-free string that the Swift app logs at launch.
/// Never carries message content or key material.
#[uniffi::export]
pub fn ping() -> String {
    format!("{CORE_NAME} {} ok", env!("CARGO_PKG_VERSION"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ping_reports_core_and_version() {
        let reply = ping();
        assert!(reply.starts_with("brev-core "));
        assert!(reply.ends_with(" ok"));
        assert!(reply.contains(env!("CARGO_PKG_VERSION")));
    }

    #[test]
    fn ping_is_pure_ascii_and_short() {
        let reply = ping();
        assert!(reply.is_ascii());
        assert!(reply.len() < 64);
    }
}
