// AppDelegate.swift — application lifecycle for Brev (Phase 0: one empty window).
//
// Upholds CLAUDE.md §1.1 and §1.5: nothing here persists anything. There is no
// state restoration, no window-frame autosave, no user defaults, no caches. The
// only log line is the content-free `ping()` reply from the Rust core (§6:
// never log content; log ids, not bodies).
//
// FFI wiring (see docs/DECISIONS.md D-0003 and app/project.yml):
// app/Generated/BrevCore.swift is compiled into
// this same target and its C symbols come from the bridging header, so `ping()`
// is a module-level function here. No `import BrevCore` / `import BrevCoreFFI`.

import AppKit
import os

final class AppDelegate: NSObject, NSApplicationDelegate {

    /// Log channel for the Rust core boundary. Only content-free diagnostics
    /// may ever be written here.
    private static let coreLog = Logger(subsystem: "no.brev.app", category: "core")

    /// Strong reference to the single main window. `MainWindow` sets
    /// `isReleasedWhenClosed = false`, so ARC owns the window through this.
    private var mainWindow: MainWindow?

    // MARK: - NSApplicationDelegate

    func applicationDidFinishLaunching(_ notification: Notification) {
        let window = MainWindow(contentSize: NSSize(width: 900, height: 600))
        window.center()
        window.makeKeyAndOrderFront(nil)
        mainWindow = window

        // macOS 14+ cooperative activation. The app was launched by the user,
        // so the system permits it to come to the front.
        NSApplication.shared.activate()

        logCorePing()
    }

    /// Secure coding for any restorable state. Brev restores nothing (every
    /// window has `isRestorable = false`), but answering `true` silences the
    /// macOS 14 warning and keeps the app on the strict path.
    func applicationSupportsSecureRestorableState(_ app: NSApplication) -> Bool {
        true
    }

    /// Closing the only window quits the app: there is nothing to keep running
    /// and no background work that could hold plaintext (§1.10).
    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
        true
    }

    // MARK: - Rust core

    /// Calls the Rust core's liveness check and logs its reply.
    ///
    /// `ping()` is generated by UniFFI from `brev-core` and returns a short
    /// version string ("brev-core 0.0.1 ok"). It is content-free by
    /// construction, which is the only reason `.public` privacy is acceptable.
    private func logCorePing() {
        let reply = ping()
        Self.coreLog.info("brev-core ping: \(reply, privacy: .public)")
    }
}
